site_name: bool-hybrid-array
site_url: https://bksell.github.io/bool-hybrid-array/
site_description: High‑performance reverse sparse boolean hybrid array for Python & Cython

plugins:
  - sitemap:
      changefreq: weekly
      priority: 0.8

theme:
  name: material
